export const cities = {
  "sao_paulo": "São Paulo - SP",
  "rio_de_janeiro": "Rio de Janeiro - RJ",
  "belo_horizonte": "Belo Horizonte - MG",
  "salvador": "Salvador - BA",
  "curitiba": "Curitiba - PR",
  "brasilia": "Brasília - DF",
  "porto_alegre": "Porto Alegre - RS",
  "manaus": "Manaus - AM",
  "recife": "Recife - PE",
  "fortaleza": "Fortaleza - CE",
  "goiania": "Goiânia - GO",
  "belem": "Belém - PA",
  "sao_luis": "São Luís - MA",
  "maceio": "Maceió - AL",
  "campo_grande": "Campo Grande - MS",
  "natal": "Natal - RN",
  "teresina": "Teresina - PI",
  "joao_pessoa": "João Pessoa - PB",
  "cuiaba": "Cuiabá - MT",
  "aracaju": "Aracaju - SE",
  "florianopolis": "Florianópolis - SC",
  "vitoria": "Vitória - ES",
  "palmas": "Palmas - TO",
  "boa_vista": "Boa Vista - RR",
  "rio_branco": "Rio Branco - AC",
  "macapa": "Macapá - AP",
  "porto_velho": "Porto Velho - RO",
};
